### ISSUE TITLE
Intellij IDEA 2021.2 Exception Report

### ISSUE THREAD

**Issue by Nasller** [viartemev/requestmapper#325]
java.lang.AbstractMethodError: Receiver class com.viartemev.requestmapper.RequestMappingItemProvider does not define or inherit an implementation of the resolved method 'abstract boolean filterElements(com.intellij.ide.util.gotoByName.ChooseByNameViewModel, java.lang.String, boolean, com.intellij.openapi.progress.ProgressIndicator, com.intellij.util.Processor)' of interface com.intellij.ide.util.gotoByName.ChooseByNameItemProvider.

 at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:291)

 at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)

 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)

 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)

 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)

 at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)

 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)

 at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)

 at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)

 at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)

 at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)

 at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)

 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)

 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)

 at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:305)

 at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)

 at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)

 at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)

 at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)

 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)

 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)

 at java.base/java.security.AccessController.doPrivileged(Native Method)

 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)

 at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by tareq021** [comment]
Hi, any update so far?

**Comment by wajncn** [comment]
Abdullah-Al-Tareq ***@***.***> 于2021年8月7日周六 上午11:54写道：

**Comment by Tomanow** [comment]
+1 Formatted stack trace:
```
java.lang.AbstractMethodError: Receiver class com.viartemev.requestmapper.RequestMappingItemProvider does not define or inherit an implementation of the resolved method 'abstract boolean filterElements(com.intellij.ide.util.gotoByName.ChooseByNameViewModel, java.lang.String, boolean, com.intellij.openapi.progress.ProgressIndicator, com.intellij.util.Processor)' of interface com.intellij.ide.util.gotoByName.ChooseByNameItemProvider.
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:305)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by stupdit1t** [comment]
已经fork原作者的项目, 升级了版本, 可查看我fork的项目,本地安装的方式就可以使用了

**Comment by viartemev** [comment]
Thanks to @stupdit1t for contribution, I will release a new version of plugin to the store if you can confirm that flow is working now.
@Tomanow @wajncn @tareq021 @Nasller 
Sorry for the long answer :)

**Comment by stupdit1t** [comment]
> 感谢@stupdit1t的贡献，如果您可以确认该流程现在正在工作，我将向商店发布新版本的插件。 @Tomanow @wajncn @tareq021 @Nasller很抱歉回答:)很长

大佬,升级这个也不麻烦啊, 你可以把我的请求merge,  然后把那个作者信息改回去

**Comment by stupdit1t** [comment]
> > 感谢@stupdit1t的贡献，如果您可以确认该流程现在正在工作，我将向商店发布新版本的插件。 @Tomanow @wajncn @tareq021 @Nasller很抱歉回答:)很长
> 
> 大佬,升级这个也不麻烦啊, 你可以把我的请求merge, 然后把那个作者信息改回去

noproblem  2021.3 version normal
