### ISSUE TITLE
"List is empty" error in 0.11 version

### ISSUE THREAD

**Issue by starman1108** [viartemev/requestmapper#90]
After upgrading 0.11 version, I am always seeing this error message.
Here is error message in intellij IDEA.

List is empty.
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:178)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.extractParameterNameWithType(SpringMappingAnnotation.kt:76)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchMappingsFromMethod(SpringMappingAnnotation.kt:62)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchRequestMappingItem(SpringMappingAnnotation.kt:22)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.values(SpringMappingAnnotation.kt:16)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:40)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:253)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at com.viartemev.requestmapper.RequestMappingContributor.findRequestMappingItems(RequestMappingContributor.kt:41)
	at com.viartemev.requestmapper.RequestMappingContributor.getNames(RequestMappingContributor.kt:18)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:98)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:82)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:120)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:80)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1434)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1410)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1392)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1356)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1343)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:178)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.extractParameterNameWithType(SpringMappingAnnotation.kt:76)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchMappingsFromMethod(SpringMappingAnnotation.kt:62)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchRequestMappingItem(SpringMappingAnnotation.kt:22)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.values(SpringMappingAnnotation.kt:16)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:40)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:253)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at com.viartemev.requestmapper.RequestMappingContributor.findRequestMappingItems(RequestMappingContributor.kt:41)
	at com.viartemev.requestmapper.RequestMappingContributor.getNames(RequestMappingContributor.kt:18)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:98)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:82)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:120)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:80)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1434)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1414)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1392)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1356)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1343)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:178)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.extractParameterNameWithType(SpringMappingAnnotation.kt:76)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchMappingsFromMethod(SpringMappingAnnotation.kt:62)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchRequestMappingItem(SpringMappingAnnotation.kt:22)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.values(SpringMappingAnnotation.kt:16)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:40)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:253)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at com.viartemev.requestmapper.RequestMappingContributor.findRequestMappingItems(RequestMappingContributor.kt:41)
	at com.viartemev.requestmapper.RequestMappingContributor.getNames(RequestMappingContributor.kt:18)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:98)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:82)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:120)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:80)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1434)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1410)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1392)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1356)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1343)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:178)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.extractParameterNameWithType(SpringMappingAnnotation.kt:76)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchMappingsFromMethod(SpringMappingAnnotation.kt:62)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchRequestMappingItem(SpringMappingAnnotation.kt:22)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.values(SpringMappingAnnotation.kt:16)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:40)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:253)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at com.viartemev.requestmapper.RequestMappingContributor.findRequestMappingItems(RequestMappingContributor.kt:41)
	at com.viartemev.requestmapper.RequestMappingContributor.getNames(RequestMappingContributor.kt:18)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:98)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:82)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:120)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:80)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1434)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1410)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1392)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1356)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1343)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:178)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.extractParameterNameWithType(SpringMappingAnnotation.kt:76)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchMappingsFromMethod(SpringMappingAnnotation.kt:62)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.fetchRequestMappingItem(SpringMappingAnnotation.kt:22)
	at com.viartemev.requestmapper.annotations.spring.SpringMappingAnnotation.values(SpringMappingAnnotation.kt:16)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:40)
	at com.viartemev.requestmapper.RequestMappingContributor$findRequestMappingItems$3.invoke(RequestMappingContributor.kt:12)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:253)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:654)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:684)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:675)
	at com.viartemev.requestmapper.RequestMappingContributor.findRequestMappingItems(RequestMappingContributor.kt:41)
	at com.viartemev.requestmapper.RequestMappingContributor.getNames(RequestMappingContributor.kt:18)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:98)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:82)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:120)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:80)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1434)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1410)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1392)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1356)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1343)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by viartemev** [comment]
@starman1108 thanks for the issue. This problem is already solved in issue #84 and will be fixed in `version 0.12.0`

**Comment by starman1108** [comment]
Thank you.
